
name: CI/CD for DVWA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      dvwa:
        image: vulnerables/web-dvwa
        ports:
          - 80:80
        options: >-
          --health-cmd="curl -f http://localhost || exit 1"
          --health-interval=30s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build DVWA
        run: docker-compose up -d

      - name: Wait for DVWA to be ready
        run: |
          sleep 10 # ожидание, пока приложение запустится
          curl -f http://localhost || exit 1

      - name: Run your tests (если есть)
        run: |
          # Здесь вы можете добавить команды для тестирования приложения
          echo "All tests passed!" # Замените на ваши команды тестирования

      - name: Clean up
        run: docker-compose down
